name: Sub Action
description: Example Sub Action

inputs:
  variable:
    description: "Variable to echo"

runs:
  using: composite
  steps:
    - name: Echo Variable
      run: echo "Sub Action One - ${{ inputs.variable }}"
      shell: bash

    - name: Echo action repository
      run: echo "Action Repo - ${{ github.action_repository }}"
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v3
