name: Pull Request Test

on:
  - pull_request

jobs:
  pr:
    runs-on: ubuntu-latest
    name: Pull Request
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check TODOs
        uses: dmsi-io/gha-code-review@fix/inverted-check
        with:
          token: ${{ secrets.GHA_ACCESS_TOKEN }}
