name: Test Sub Actions

on:
  workflow_call:
  push:

jobs:
  external-sub-actions:
    runs-on: ubuntu-latest
    name: Test External Sub Actions
    steps:
      - name: Run Sub Action
        uses: alehechka/gha-playground/sub-action@main
        with:
          variable: "testing external reference call - ${{ github.action_repository }}"

  internal-sub-actions:
    runs-on: ubuntu-latest
    name: Test Internal Sub Actions
    steps:
      - uses: actions/checkout@v3

      - name: Run Sub Action
        uses: ./sub-action
        with:
          variable: "testing internal reference call - ${{ github.action_repository }}"

      - name: Cat README
        run: cat README.md
